### ISSUE TITLE
Spilt up parsing and the rewrite engine into two files

### ISSUE THREAD

**Issue by TheKnarf** [contrast-zone/rewrite.js#2]
I can imagine a lot of useful use cases where I care about having a rewrite engine, but not a whole lot about a specific DSL. Let's for example say that I want to implement a new computer aided algebra system, or an optimisation in a compiler stage; in those cases I'd like to reuse an existing rewrite engine so that I don't have to reinvent the wheel, but I don't want to write a new DSL since it should work with the product I'm writing (like a CAS or a compiler).

The DSL is mostly useful for people who want to use the tool as a standalone tool and not as a library in their own application. If every JavaScript library implemented their own DSL with a custom parser then you would no longer be writing JavaScript but instead a bunch of different DSL's.

This is my biggest gripe with rewrite systems like [Maude](http://maude.cs.illinois.edu/w/index.php/The_Maude_System), you spend more time learning the specific language than actually using it for anything productive, and its non-obvious how to actually integrate it in a product and not just as a toy.

**Comment by contrast-zone** [comment]
Thank you, that's a good proposition.

**Comment by contrast-zone** [comment]
Split `rewrite (...)` to `rewrite.parse(...)` and `rewrite.reduce(...)` function.
